# Ejercicios de Numpy
Inteligencia Artificial - Facundo A. Lucianna - CEIA - FIUBA

A continuación veamos ejercicios de Numpy que deben resolver.

Ejercicio 1: Importa a Numpy como np

In [1]:
import numpy as np

Ejercicio 2: Crea un array de la siguiente lista

In [4]:
lista = [1, 2, 3, 4, 5]
lista_array = np.array(lista)
lista_array

array([1, 2, 3, 4, 5])

Ejercicio 3: Suma los siguientes dos arrays

In [6]:
a = np.array([[1,2,3],
              [4,5,6]])

b = np.array([[10,11,12],
              [13,14,15]])

In [7]:
a+b

array([[11, 13, 15],
       [17, 19, 21]])

Ejercicio 4: Multiplica por 3.2 al siguiente array (una matriz)

In [8]:
a = np.array([[4,2,2],
              [4,1,0]])

In [9]:
a*3.2

array([[12.8,  6.4,  6.4],
       [12.8,  3.2,  0. ]])

Ejercicio 5: Convierta en una matriz cuadrada al siguiente array unidimensional.

1. Usando shape fijate que dimension tiene el array
2. Usando .reshape() convierta al array en una matriz cuadrada


In [16]:
a = np.array([x for x in range(9)])

a_cuadrada = np.reshape(a, (3,3))
a_cuadrada

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Ejercicio 6: Convierta el tipo del siguiente array en entero (int)

In [17]:
a = np.array([[2.5, 3.8, 1.5],
              [4.7, 2.9, 1.56]])


In [20]:
a_int = a.astype(int)
print(a_int)

[[2 3 1]
 [4 2 1]]


Ejercicio 7: Crea una matriz de identidad de orden 5 (usando np.eye) y luego transforma el tipo en booleano (bool)

In [22]:
a = np.eye(5)

In [24]:
bool_matrix_5 = a.astype(bool)
bool_matrix_5

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True, False],
       [False, False, False, False,  True]])

Ejercicio 8: Cocatena de forma horizontal (una al costado de la otra) los siguientes arrays

In [25]:
a1 = np.array([[1,2,3],
               [4,5,6]])

a2 = np.array([[7,8,9],
               [10,11,12]])



In [28]:
a1_2 = np.concatenate((a1,a2), axis=1)

a1_2

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

Ejercicio 9: Cocatena de forma vertical los mismos array

In [30]:
a1_2_v = np.concatenate((a1,a2), axis=0)
a1_2_v

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

Ejercicio 9: Crea un array unidimensional que tenga los numeros de 0 a 100 (incluido) con saltos de 2.

In [33]:
a= np.array([x for x in range(0,101,2)])
a

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

Ejercicio 10: Usando np.where() compara en que elementos el array **a** es mayor al array **b**

In [35]:
a = np.array([1,2,3,4,6])

b = np.array([1,3,2,4,5])

In [37]:
np.where(a > b)

(array([2, 4]),)

Ejercicio 11: Genera en un array una secuencia separada de forma equidistante de 5 numeros que van de 0 a 100 (inclusive ambos)

In [38]:
a= np.array([x for x in range(0,101,5)])
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100])

In [39]:

a = np.arange(0, 101, 5)
print(a)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100]


Ejercicio 12: Crea una matriz de 2x3 con todos los valores igual a 23 (Hint: podes usar [np.full](https://numpy.org/doc/stable/reference/generated/numpy.full.html) o [np.eye](https://numpy.org/devdocs/reference/generated/numpy.eye.html))


In [41]:
a= np.full((2,3),23)
a

array([[23, 23, 23],
       [23, 23, 23]])

Ejercicio 13: Crea un array de 8x2 numeros aleatorios que sigan la distribucion normal (Hint: [np.random.normal](https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html))

In [44]:
np.random.normal(loc=0.0, scale=1.0, size=(8,2))


array([[ 0.02760752,  0.40253818],
       [-1.33028231,  0.84771921],
       [-0.63987624, -0.22605377],
       [-0.75396184, -0.73444147],
       [-1.85143014, -1.41634314],
       [ 0.96281709, -1.15730216],
       [-0.10330454, -0.02519793],
       [-1.53876986,  0.316888  ]])

Ejercicio 14: Dadas las siguientes matrices, multipliquelas como matrices. Luego multipliquelas como si fueran arrays

In [45]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

b = np.array([[2,3,4],
              [5,6,7],
              [8,9,10]])

In [46]:
np.matmul(a,b)

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

In [47]:
a*b

array([[ 2,  6, 12],
       [20, 30, 42],
       [56, 72, 90]])

In [48]:
a@b

array([[ 36,  42,  48],
       [ 81,  96, 111],
       [126, 150, 174]])

Ejercicio 15: Dado el siguiente array, ordenelo de forma ascendente (Hint: [np.argsort](https://numpy.org/doc/stable/reference/generated/numpy.argsort.html)). Luego de forma descendente.

In [69]:
a = np.array([1, 0, 82, 2, 939, 91, 1101, 199, 292, 2, 923, 387, 38, 299])

In [70]:
indices_asc = np.argsort(a)
a_sorted_asc = a[indices_asc]

print("Ascendente:", a_sorted_asc)

Ascendente: [   0    1    2    2   38   82   91  199  292  299  387  923  939 1101]


----

Ejercicio 16: Lee el csv venta_libros en un array. Luego separa las columnas en 3 arrays diferentes, el primero llamado year, el segundo month, y el tercero books

In [78]:
import os
print(os.getcwd())

c:\Users\60080956\Documents\CEIA\intro_ia\clase1\ejercicios


In [85]:
# Import csv data

# Cambia la ruta al archivo según corresponda. Si está en el mismo directorio:
venta_libros_data = np.loadtxt(r'datasets/venta_libros.csv', delimiter=',', skiprows=1)

Usando np.max() obtenga el valor de ventas de libros más alto. Luego, busque a que mes y años corresponde

In [92]:
max_ventas=np.max(venta_libros_data[:,2])
fila_max=np.argmax(venta_libros_data[:,2])

In [96]:
print(f"Ventas: {float(max_ventas)}")
print(f"Año: {int(venta_libros_data[fila_max,0])}")
print(f"Mes: {int(venta_libros_data[fila_max,1])}")

Ventas: 489.0
Año: 2021
Mes: 8


Calcula las ventas totales, las ventas promedio, la mediana de las ventas y el desvio estandar (Hint: [np.sum](https://numpy.org/doc/stable/reference/generated/numpy.sum.html), [np.mean](https://numpy.org/doc/stable/reference/generated/numpy.mean.html), [np.median](https://numpy.org/doc/stable/reference/generated/numpy.median.html), [np.std](https://numpy.org/doc/stable/reference/generated/numpy.std.html))

In [97]:
np.sum(venta_libros_data[:,2])

np.float64(12436.0)

In [98]:
np.mean(venta_libros_data[:,2])

np.float64(264.59574468085106)

In [99]:
np.median(venta_libros_data[:,2])

np.float64(276.0)

In [100]:
np.std(venta_libros_data[:,2])

np.float64(136.14223781788837)